# --- docker-compose.yml ---
version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1